name: Generate Documentation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd docs/maker_documentation
          pip install -r requirements.txt

      - name: Run main script
        run: |
          cd docs/maker_documentation
          python main.py

      - name: Force file modification with touch
        run: |
          touch docs/md_docs/software-list.md
          touch docs/md_docs/soup-list.md

      - name: Add and commit changes
        run: |
          git add docs/md_docs/software-list.md
          git add docs/md_docs/soup-list.md
          git commit -m "Aggiornamento documentazione" || echo "Nessuna modifica da committare"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up untracked files
        run: |
          git clean -fdX  # Rimuove file come __pycache__
