name: Generate Documentation

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          # Cerca e installa le dipendenze dal file requirements.txt se esiste
          REQUIREMENTS_FILE=$(find . -name "requirements.txt" | head -n 1)
          if [ -f "$REQUIREMENTS_FILE" ]; then
            echo "Found requirements.txt at $REQUIREMENTS_FILE"
            pip install -r "$REQUIREMENTS_FILE"
          else
            echo "No requirements.txt found"
          fi

      - name: Run main script
        run: |
          cd docs/maker_documentation
          python main.py

      - name: Set up Git config
        run: |
          git config --global user.email "author_email"
          git config --global user.name "author_name"

      - name: Commit and push changes
        run: |
          cd docs
          # Aggiungi i file specificati
          git add md_docs/software-list.md
          git add md_docs/soup-list.md
          
          # Aggiungi direttamente requirements.txt
          git add requirements.txt
          
          # Aggiungi previous_json_list.json
          git add previous_json_list.json

          # Effettua il commit e push delle modifiche
          git commit -m 'Update documentation files and requirements' || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
