name: Generate Documentation

on:
  push:
    branches:
      - '**'  # Esegui il workflow su tutti i branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd docs/maker_documentation
          pip install -r requirements.txt

      - name: Run main script
        run: |
          cd docs/maker_documentation
          python main.py  # Esegui lo script che genera i file di documentazione

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Check for changes
        run: |
          cd docs
          git status  # Mostra lo stato dei file
          git add -A  # Aggiungi tutte le modifiche
          git diff --cached --exit-code || (git commit -m 'Update documentation files' && echo "Changes committed") || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}  # Push al branch corrente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

